# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ac1129af5b4e56a0278b1855bfd6f1ab"
name = "choco-app"
handle = "choco-app-48"
application_url = "https://surprised-divorce-broadcasting-vacations.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "kefi-aditya.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_products"

[auth]
redirect_urls = [
  "https://surprised-divorce-broadcasting-vacations.trycloudflare.com/auth/callback",
  "https://surprised-divorce-broadcasting-vacations.trycloudflare.com/auth/shopify/callback",
  "https://surprised-divorce-broadcasting-vacations.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
